=== aashish1502/IWP-FAT-hacks/person.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="person" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="FirstName" type="xs:string"></xs:element>
                                        <xs:element name="LastName" type="xs:string"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="age" type="xs:integer"></xs:element>
                            <xs:element name="address" type="xs:string"></xs:element>
                            <xs:element name="phone" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== aashish1502/IWP-FAT-hacks/person.xml
<?xml version="1.0" encoding="UTF-8"?>

<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="person.xsd">
    <person>
        <name>
            <FirstName>Aashish</FirstName>
            <LastName>Sharma</LastName>
        </name>
        <age>20</age>
        <address>Earth</address>
        <phone>call me maybe</phone>
    </person>

    <person>
        <name>
            <FirstName>Sanskrita</FirstName>
            <LastName>Saha</LastName>
        </name>
        <age>20</age>
        <address>Earth</address>
        <phone>call me maybe</phone>
    </person>
</root>
