=== aashish1502/IWP-FAT-hacks/XML/real-estate/real_estate.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="real-estate">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Agencies" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="email" type="xs:string"></xs:element>
                            <xs:element name="phone" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Owner" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Properties" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="numberofflats" type="xs:integer"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Flat" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="description" type="xs:string"></xs:element>
                            <xs:element name="rate" type="xs:integer"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== aashish1502/IWP-FAT-hacks/XML/real-estate/real_estate.xml
<?xml version="1.0" encoding="UTF-8"?>
<real-estate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="real_estate.xsd">
    <Agencies>
        <name>Aashish</name>
        <email>aashish@gmail.com</email>
        <phone>9876564321</phone>
    </Agencies>
    <Owner>
        <name>Sanskrita</name>
    </Owner>
    <Properties>
        <name>Adonis Group</name>
        <numberofflats>5</numberofflats>
    </Properties>
    <Flat>
        <name>Adonis Residency</name>
        <description>A 3bhk flat</description>
        <rate>700000</rate>
    </Flat>
</real-estate>
